version: '3.8'

services:
  servicerp:
    image: rpaasoneboxacr.azurecr.io/rpaas-onebox/servicerp
    ports:
      - "6012:6012"
    volumes:
      - "file-db:/root/.local/share/rpsaas/fileDBData"

  metarp:
    image: rpaasoneboxacr.azurecr.io/rpaas-onebox/metarp
    ports:
      - "6010:6010"
    volumes:
      - "file-db:/root/.local/share/rpsaas/fileDBData"

  webserver:
    image: nginx:alpine
    ports:
      - "6000:80"
    volumes:
      - "./nginx.conf:/etc/nginx/nginx.conf"
    depends_on:
      - servicerp
      - metarp

volumes:
  file-db:
