# Verify PR

trigger: none
pr:
  - master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.x'
  displayName: 'Install Node.js'

- script: node common/scripts/install-run-rush.js change -v
  displayName: "Verify change files"

- script: node common/scripts/install-run-rush.js install
  displayName: "Install Dependencies"

- script: node common/scripts/install-run-rush.js rebuild
  displayName: Build

- script: node common/scripts/install-run-rush.js test
  displayName: Test

- script: |
    cd packages/adl
    npm link
    npx adl generate samples/confluent/ --client
  displayName: "Sanity Check Client Generation"
