trigger: none
pr:
  - master

pool:
  vmImage: windows-2019

steps:
  - script: echo '##vso[task.setvariable variable=ADL_REQUIRE_VS_BUILD;]true'
    displayName: Enable Visual Studio extension build

  - template: pull-request-common.yml
