# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: "Release"

steps:
  - script: dotnet pack ./packages/Cadl.RPaasController.Common --configuration $(buildConfiguration)
    displayName: "Build and publish RPaasController.Common"
  - task: NuGetCommand@2
    inputs:
      command: "push"
      packagesToPush: "./packages/Cadl.RPaasController.Common/**/*.nupkg"
      nuGetFeedType: "internal"
      publishVstsFeed: "29ec6040-b234-4e31-b139-33dc4287b756/fa8c16a3-dbe0-4de2-a297-03065ec1ba3f"
